### ISSUE TITLE
Someone must change decduction to deduction

### ISSUE THREAD

**Issue by quantuumsnot** [freeCodeCamp/donate#3]
https://github.com/freeCodeCamp/donate/blob/899606b871f04a8d125d458195172abfd58fc51f/index.html#L130

**Comment by raisedadead** [comment]
Fixed in #4

**Comment by pdurbin** [comment]
I see that pull request #4 was merged but I'm still seeing "decduction" at https://donate.freecodecamp.org

Maybe the code hasn't been deployed yet?

**Comment by raisedadead** [comment]
Hi @pdurbin !

This should be deployed any minute now. I think the build did not trigger as expected previously.

Thanks for letting us know.
